### ISSUE TITLE
Not working as expected in Vaadin 7.6.3(+)?

### ISSUE THREAD

**Issue by steffen-harbich-itc** [alump/LazyLayouts#7]
I like your add-on but I have problems getting it to work as expected. I tried several things to get it running:

- Placed under TabSheet
No lazy loading is done and it gives the JavaScript warning:
Sun Jan 08 17:05:26 GMT+100 2017 org.vaadin.alump.lazylayouts.client.LazyVerticalLayoutConnector
SEVERE: Failed to connect to scrolling events of com.vaadin.client.ui.tabsheet.TabsheetConnector

- Placed under Panel
This loads next content over and over again without waiting for the user to scroll down.

- Placed under Window
This resets the scroll position to top when content was lazy loaded.

I tried Vaadin versions 7.6.3 and 7.7.6, both with the same issues. Would be nice if you can have a look at it. Maybe something has changed in new Vaadin versions.

Have a nice day,
Steffen

**Comment by alump** [comment]
I need to have look at this soon, and also verify functionality with Vaadin 8.

**Comment by gentle9** [comment]
I am trying to use this addon with Vaadin 8.1.0 within a normal Panel (which is in an other VerticalSplitPanel as second component) and the first loading of the contents seems to work fine.
But then it doesn´t reload the next content if the user scrolls down. The loading animation is shown but nothing happens. The listener onLazyComponentRequest is never called again after the first time.

**Comment by alump** [comment]
https://github.com/alump/LazyLayouts/blob/master/lazylayouts-demo/src/main/java/org/vaadin/alump/lazylayouts/demo/Issue7View.java - I made this test with 8.1.1 and it worked.

**Comment by alump** [comment]
Check that you didn't define height of LazyVerticalLayout inside the panel. Also the panel should have it's height defined (usually 100% if you want it to take all available space in half of SplitPanel).

**Comment by alump** [comment]
Closing as no response.
