### ISSUE TITLE
Please make LazyComponentProvider extend Serializable

### ISSUE THREAD

**Issue by mvysny** [alump/LazyLayouts#9]
If one writes code as follows:
```
vl.enableLazyLoading(new LazyComponentProvider() {
...
});
```
Then that provider is not Serializable, and e.g. Tomcat will complain later on that
```
Apr 03, 2017 4:17:50 PM org.apache.catalina.session.StandardSession doWriteObject
WARNING: Cannot serialize session attribute com.vaadin.server.VaadinSession.MyUIServlet for session D69B79DCA3E3FBEE840CC9E7D1C185DC
java.io.NotSerializableException: org.test.MyUI$1
```
Thanks! ;)

**Comment by alump** [comment]
What version do you use (read: do you have Vaadin 7 or Vaadin 8 project)

**Comment by alump** [comment]
0.2.1 has this fixed, if required I can also add it to Vaadin 7 versions (0.1.x)

**Comment by alump** [comment]
0.1.4 also has this fix now (for Vaadin 7 users)

**Comment by mvysny** [comment]
Thanks so much! I'm using Vaadin 8. Thanks for fixing :)
